scraper/config/routes.rb
Rails.application.routes.draw do
  # get 'analytic/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  get 'analytic', to: 'analytic#index'
  get 'categories', to: 'categories#index'
  get 'categories_inline', to: 'categories#categories_inline'
  get 'testing_data', to: 'testing_data#index'
  get 'api_chat', to: 'api_chat#index'

  get 'scraper', to: 'scraper#index'

  get 'scraper_companies', to: 'scraper#companies'
  get 'scraper_one_company', to: 'scraper#one_company'

  get 'scraper_people', to: 'scraper#people'
  get 'scraper_one_person', to: 'scraper#one_person'

  get 'scraper_one_job', to: 'scraper#one_job'
  get 'scraper_list_jobs', to: 'scraper#list_jobs'
  get 'scraper_set_authorization', to: 'scraper#set_authorization'

  get 'scraper_testing', to: 'scraper#testing'

end

scraper/app/views/layouts/shared/_cookies_modal.html.erb
<% if cookies[:cookies_accepted].nil? %>

  <div class="modal fade" id="cookiesModal" aria-labelledby="cookiesModalLabel" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">WE VALUE YOUR PRIVASY</h5>
        </div>
        <div class="modal-body">
          <p>We use cookies to improve your experience on our website. We use the most minimal
            set of information about your visit.</p>

          <p>Please note that your consent will be valid for all of our subdomains.
            You can change or withdraw your consent at any time. We respect your choice
            and are committed to providing you with a transparent and safe browsing experience.
            <%= link_to 'Privacy & security', privacy_policy_path %>
          </p>
        </div>
        <div class="modal-footer">
          <%= button_to "Accept cookies", cookies_path(accept_cookies: true), method: :post, class: "btn btn-sm btn-success" %>
          <%= button_to "Reject cookies", cookies_path(accept_cookies: false), method: :post, class: "btn btn-sm btn-secondary" %>
        </div>
      </div>
    </div>
  </div>
  <script>
    setTimeout(function () {
      $('#cookiesModal').modal('show');
    }, 3000);
  </script>

<% end %>

scraper/app/views/layouts/shared/_errors.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-dismissible fade show" role="alert" id="<%= type %>">
    <% if msg.is_a?(Array) %>
      <%= msg.join(', ') %>
    <% else %>
      <%= msg %>
    <% end %>

    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<script>
  window.addEventListener("load", function () {
    window.setTimeout(function () {
      $(".alert").fadeTo(1000, 0).slideUp(500, function () {
        $(this).remove();
      });
    }, 5000);
  });
</script>

scraper/app/views/layouts/shared/_footer.html.erb
<footer class="<%= fixed ? 'fixed-bottom' : '' %>">
  <div class='container'>
    <div class='footer-wrapper'>
      <div class ="headline-wrapper">
        <div class="headline-logo">
          <%= link_to root_path, class: 'navbar-brand' do %> 
            <%= image_tag 'logos/footer-logo-orange.png' %>
          <% end %>
        </div>
        <div class="headline-media" style='display: none;'>
          <h2>Headline Media Logos</h2>
        </div>
      </div>    

      <div class='row'>
        <div class='col-3'>
          <ul class='list-unstyled'>
            <li><%= link_to 'Official rules', official_rules_path, class: 'nav-link' %></li>
            <li><%= link_to 'Terms & Conditions', terms_conditions_path, class: 'nav-link' %></li>
            <li><%= link_to 'Privacy Policy', privacy_policy_path, class: 'nav-link' %></li>
            <li><%= link_to 'FAQ', faq_path, class: 'nav-link' %></li>
          </ul>
        </div>
        <div class='col-3'>
          <ul class='list-unstyled'>
            <li><%= link_to 'Contact Us', contact_us_path, class: 'nav-link' %></li>
            <li>Careers</li>
            <li><%= link_to 'Press Kit', press_kit_path, class: 'nav-link' %></li>
          </ul>
        </div>
        <div class='col-3'>
          <ul class='list-unstyled'>
            <li><%= link_to 'About Us', about_us_path, class: 'nav-link' %></li>
            <li><%= link_to 'News', news_index_path, class: 'nav-link' %></li>
            <li><%= link_to 'Shop', spree_path, target: 'new', class: 'nav-link' %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

scraper/app/views/layouts/shared/_navbar.html.erb
<div class='container'>
  <ul class="dropdown-menu dropdown-menu-center" aria-labelledby="accountDropdown">
    <%= link_to 'BASE', root_path, class: 'dropdown-item' %> |
    <%= link_to 'expressions', analytic_path, class: 'dropdown-item' %> |
    <%= link_to 'categories_each_occurrences', categories_path, class: 'dropdown-item' %> |
    <%= link_to 'categories_inline', categories_inline_path, class: 'dropdown-item' %> |
    <%= link_to 'testing_data', testing_data_path, class: 'dropdown-item' %> |
    <br>
    <hr>

    <%= link_to 'FULL-JOBS', scraper_path, class: 'dropdown-item' %> |
    <%= link_to 'Get_LINKS_of_Jobs', scraper_list_jobs_path, class: 'dropdown-item' %> |
    <%= link_to 'Get_each_JOB', scraper_one_job_path, class: 'dropdown-item' %> |
    <br>
    <hr>

    <%= link_to 'Companies_List', scraper_companies_path, class: 'dropdown-item' %> |
    <%= link_to 'Get_each_Company', scraper_one_company_path, class: 'dropdown-item' %> |
    <br>
    <hr>

    <%= link_to 'People_List', scraper_people_path, class: 'dropdown-item' %> |
    <%= link_to 'Get_each', scraper_one_person_path, class: 'dropdown-item' %> | | | | |

    <%= link_to 'TESTING', scraper_testing_path, class: 'dropdown-item' %>
  </ul>
</div>